name: CodeSonar
on:
  push:                  # Only run onces the Pull request is created
    branches:
      - 'release/**'               # Feature Branches
  pull_request:
    branches:
      - 'release/**'       
  
jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: WINDOWS # Requires Python, CodeSonar and Visual Studio Community to be installed on the runner.
                     # also requires the python packages requests and urllib3 to be installed.
    env:
      CAFILE: ".github/github.cert.pem" 
      TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      API_URL: https://api.github.com
      REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "OSS-Projects/PdfPig-GitHub" 
      PROJECT_NAME: "PdfPig"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com" 
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASSWORD }}"
      CSONAR_CSHOME: "C:\\Program Files\\CodeSecure\\CodeSonar"
      #CS_USER_HOME: /__w/iris/iris
      COMMIT_HASH: ${{ github.sha }}
      REPO_URL: "https://github.com/CodeSecure-SE/PdfPig"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:

      - name: Checkout 
        uses: actions/checkout@v4
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          ref: windows
          path: cso-scripts

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # Build the release build
      - name: Build the solution
        run: dotnet build -c Release src/UglyToad.PdfPig.sln 
      - name: widen policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
#      - run: pip install requests 
      - name: check python version
        run: python --version
      - name: Build and Analyze
#        run: python -v cso-scripts\build_and_analyze.py  codesonar.conf cs-dotnet-scan -include-artifacts  src/UglyToad.PdfPig.Core/bin/Release/net8.0/*.dll
        run: python -v cso-scripts\build_and_analyze.py  
      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@v2
        with: 
          filePath: warnings.md
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: warnings.sarif
          category: "CodeSecure CodeSonar"            